name: Go Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          only-new-issues: true
